import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { BookOpen, BarChart3, Wheat, Flame, Droplets, Beef, Coffee, ShieldAlert, Calculator, Map, GraduationCap, CheckCircle2, XCircle, Search, ChevronRight, ChevronLeft, Layers, Clock, DollarSign, AlertTriangle } from "lucide-react";

function Card({ className = "", children }) { return <div className={`bg-white border border-zinc-200 ${className}`}>{children}</div>; }
function CardContent({ className = "", children }) { return <div className={className}>{children}</div>; }
function Button({ variant = "default", className = "", disabled, children, ...props }) {
  const styles = variant === "outline" ? "border border-zinc-300 bg-white text-zinc-900 hover:bg-zinc-100" : "border border-zinc-900 bg-zinc-900 text-white hover:bg-zinc-800";
  return <button disabled={disabled} className={`${styles} px-4 py-2 font-semibold transition disabled:opacity-40 disabled:cursor-not-allowed ${className}`} {...props}>{children}</button>;
}

const modules = [
  { id: "foundation", title: "1. Futures Foundations", icon: BookOpen, summary: "What a futures contract is, why futures exist, and how producers, consumers, and speculators use them.", lessons: [
    { title: "What is a futures contract?", body: "A futures contract is a standardized agreement to buy or sell a specific quantity of a commodity at a future date. Most retail traders close the position before delivery. The exchange standardizes contract size, months, tick value, delivery rules, and margin requirements.", takeaway: "You are not buying a barrel of oil or a bushel of corn directly. You are trading a standardized financial claim tied to that commodity." },
    { title: "Who trades futures?", body: "Hedgers use futures to reduce business risk. Farmers may sell grain futures to lock in prices. Food companies may buy futures to stabilize input costs. Speculators take the other side, attempting to profit from price moves.", takeaway: "Futures markets are built around risk transfer. Speculators provide liquidity but inherit volatility." },
    { title: "Cash vs futures", body: "The cash market is the physical spot market. Futures are exchange-traded contracts for future delivery. Futures prices reflect expected spot prices, storage costs, financing, insurance, convenience yield, seasonality, and positioning.", takeaway: "Futures prices are not just forecasts. They embed carrying costs, scarcity, and market structure." }
  ]},
  { id: "contract", title: "2. Contract Anatomy", icon: Layers, summary: "Learn symbols, tick values, contract months, notional value, margin, and delivery mechanics.", lessons: [
    { title: "Contract size and notional value", body: "Every futures contract represents a fixed quantity. Corn is 5,000 bushels. Crude oil is 1,000 barrels. Gold is 100 troy ounces. Notional value equals futures price multiplied by contract size.", takeaway: "A small price move can represent a large dollar move because each contract controls a large notional amount." },
    { title: "Tick size and tick value", body: "The tick is the minimum price increment. Tick value is the dollar value of one tick. For example, corn trades in quarter-cent increments per bushel, and one tick equals $12.50 per contract.", takeaway: "Before trading any contract, know the tick value. It defines how fast your P&L moves." },
    { title: "Contract months", body: "Each commodity has listed delivery months. Traders choose a specific month, such as December corn or March wheat. The front month is the nearest active contract. Deferred contracts expire further in the future.", takeaway: "You do not simply trade 'corn.' You trade a specific corn contract month." },
    { title: "Delivery risk", body: "Many futures are physically deliverable. Retail traders generally close or roll before first notice day and last trading day. Failing to understand these dates can create operational problems.", takeaway: "Know first notice day and last trading day. Do not improvise near expiration." }
  ]},
  { id: "markets", title: "3. Commodity Market Map", icon: Map, summary: "Energy, metals, grains, softs, livestock, and niche contracts—and what drives each market.", lessons: [
    { title: "Agriculture", body: "Corn, soybeans, wheat, cotton, coffee, cocoa, sugar, orange juice, rice, cattle, and hogs are shaped by weather, crop cycles, disease, export demand, feed demand, storage, and government reports.", takeaway: "Agriculture is rich in public but fragmented information, making it attractive for information-synthesis strategies." },
    { title: "Energy", body: "Crude oil, gasoline, heating oil, natural gas, and power-linked markets are driven by production, inventories, refining, pipelines, geopolitics, weather, and demand cycles.", takeaway: "Energy markets are liquid but often crowded. Regional bottlenecks can still create inefficiencies." },
    { title: "Metals", body: "Gold and silver are monetary and macro-sensitive. Copper is cyclical and industrial. Platinum and palladium depend heavily on auto catalyst demand. Smaller battery metals often trade through equities or physical indexes rather than liquid futures.", takeaway: "Metals require understanding both macro and physical supply chains." },
    { title: "Softs and niche markets", body: "Coffee, cocoa, sugar, cotton, orange juice, rice, and lumber can be highly inefficient because they are thinner, more weather-sensitive, and more dependent on localized information.", takeaway: "The weird markets are often where information latency is highest." }
  ]},
  { id: "structure", title: "4. Curves, Spreads, and Seasonality", icon: BarChart3, summary: "Understand contango, backwardation, calendar spreads, basis, storage, and seasonal patterns.", lessons: [
    { title: "Contango and backwardation", body: "Contango means deferred futures trade above nearby futures, often because storage and financing costs matter. Backwardation means nearby futures trade above deferred futures, often because immediate supply is scarce.", takeaway: "The futures curve tells you about inventory pressure, scarcity, and carry economics." },
    { title: "Calendar spreads", body: "A calendar spread buys one contract month and sells another in the same commodity. Spreads can isolate supply-demand changes while reducing outright price exposure.", takeaway: "Professional commodity traders often focus more on spreads than outright direction." },
    { title: "Basis", body: "Basis is the difference between local cash price and futures price. It reflects transportation, storage, local supply-demand, and quality. Strong basis can reveal physical tightness before futures fully react.", takeaway: "Basis is often where the physical market whispers before the futures market shouts." },
    { title: "Seasonality", body: "Agricultural commodities follow planting, growing, harvest, and export seasons. Energy follows heating and cooling demand. Livestock follows biological cycles. Seasonal tendencies matter, but they are not rules.", takeaway: "Seasonality is context. It is useful only when combined with current conditions." }
  ]},
  { id: "data", title: "5. Data and Information Sources", icon: Search, summary: "The reports, datasets, and unstructured signals serious commodity traders monitor.", lessons: [
    { title: "Government reports", body: "USDA reports, CFTC Commitments of Traders, EIA energy inventories, crop progress, export sales, WASDE, and acreage reports are market-moving. Learn their release schedules and typical surprise channels.", takeaway: "Public reports move markets because they synchronize expectations." },
    { title: "Weather data", body: "Weather is central to agriculture, natural gas, power, and sometimes shipping. Important variables include precipitation, temperature anomalies, soil moisture, growing degree days, frost risk, hurricanes, drought maps, and model revisions.", takeaway: "The edge is usually not knowing the weather. It is knowing what changed versus expectations." },
    { title: "Positioning and sentiment", body: "CFTC COT data shows commercial, managed money, and other trader positioning. Extreme positioning can amplify reversals or fuel momentum. It is not a standalone signal.", takeaway: "Positioning tells you how crowded the boat is. It does not tell you when it sinks." },
    { title: "Unstructured edge sources", body: "Local farm bulletins, extension reports, port updates, crop disease notes, shipping congestion, regional news, industry forums, and company commentary are harder to aggregate. This is where LLM agents can shine.", takeaway: "Your agent should convert messy local signals into structured global implications." }
  ]},
  { id: "risk", title: "6. Risk, Margin, and Position Sizing", icon: ShieldAlert, summary: "Margin, leverage, stop logic, volatility, drawdowns, contract roll, and operational risk.", lessons: [
    { title: "Initial and maintenance margin", body: "Initial margin is the amount required to open a position. Maintenance margin is the minimum equity needed to keep it. If your account falls below maintenance, you may receive a margin call.", takeaway: "Margin is not the cost of the position. It is collateral against a much larger notional exposure." },
    { title: "Mark-to-market", body: "Futures are marked to market daily. Gains and losses are credited or debited as the market moves. This creates immediate cash-flow pressure even if your thesis is ultimately right.", takeaway: "Being right later does not help if you cannot survive the path." },
    { title: "Volatility and sizing", body: "Position sizing should consider average true range, contract dollar volatility, account size, liquidity, and stop distance. Thin markets can gap through stops.", takeaway: "Size positions by dollars at risk, not by how strongly you feel." },
    { title: "Roll and expiration", body: "Rolling means closing an expiring contract and opening a later month. Roll yield can help or hurt depending on the curve. Delivery calendars matter.", takeaway: "A futures trade includes price direction, contract selection, and timing." }
  ]},
  { id: "systems", title: "7. Trading Systems and LLM Agents", icon: GraduationCap, summary: "How to design a research workflow, signal engine, backtest, alert system, and human execution process.", lessons: [
    { title: "Separate signal from execution", body: "Your agent should produce structured signals: what changed, why it matters, affected contracts, confidence, expected horizon, and invalidation criteria. Your execution system decides whether and how to trade.", takeaway: "Do not let a language model directly place trades. Use it to structure information and surface hypotheses." },
    { title: "State tracking", body: "Commodity edge often comes from detecting changes versus the prior state: wetter than expected, lower crop condition than last week, more export demand than consensus, tighter basis than normal. Maintain a living market memory.", takeaway: "The question is not 'what happened?' It is 'what changed?'" },
    { title: "Signal scoring", body: "A good score should include direction, magnitude, confidence, time horizon, source quality, novelty, and crowdedness. Weak signals should be logged, not traded.", takeaway: "Your first goal is a clean signal journal, not automation." },
    { title: "Backtesting pitfalls", body: "Commodity backtests fail when they ignore contract rolls, look-ahead bias, survivorship bias, transaction costs, slippage, report release times, and liquidity constraints.", takeaway: "A pretty backtest can be worse than no backtest if it teaches false confidence." }
  ]}
];

const markets = [
  { name: "Corn", symbol: "ZC", venue: "CBOT/CME", group: "Grains", drivers: "US Midwest weather, ethanol, feed demand, exports, USDA", inefficiency: 6, difficulty: 5, liquidity: 9, icon: Wheat },
  { name: "Soybeans", symbol: "ZS", venue: "CBOT/CME", group: "Oilseeds", drivers: "China demand, crush margins, Brazil/US weather, biofuels", inefficiency: 6, difficulty: 6, liquidity: 9, icon: Wheat },
  { name: "Wheat", symbol: "ZW/KE/MW", venue: "CBOT/KC/MGEX", group: "Grains", drivers: "Black Sea risk, drought, crop quality, export flows", inefficiency: 7, difficulty: 7, liquidity: 8, icon: Wheat },
  { name: "Coffee", symbol: "KC", venue: "ICE", group: "Softs", drivers: "Brazil/Vietnam weather, frost, crop cycle, inventories", inefficiency: 8, difficulty: 8, liquidity: 7, icon: Coffee },
  { name: "Cocoa", symbol: "CC", venue: "ICE", group: "Softs", drivers: "West Africa weather, disease, politics, grind demand", inefficiency: 8, difficulty: 8, liquidity: 7, icon: Coffee },
  { name: "Sugar", symbol: "SB", venue: "ICE", group: "Softs", drivers: "Brazil cane, ethanol parity, India policy, weather", inefficiency: 7, difficulty: 7, liquidity: 8, icon: Droplets },
  { name: "Cotton", symbol: "CT", venue: "ICE", group: "Softs", drivers: "US/India/China weather, apparel demand, trade policy", inefficiency: 8, difficulty: 8, liquidity: 7, icon: Wheat },
  { name: "Orange Juice", symbol: "OJ", venue: "ICE", group: "Niche Ag", drivers: "Florida/Brazil supply, citrus greening, hurricanes, frost", inefficiency: 10, difficulty: 9, liquidity: 3, icon: Droplets },
  { name: "Rough Rice", symbol: "ZR", venue: "CBOT/CME", group: "Niche Ag", drivers: "Asia policy, monsoon, export controls, US Delta crop", inefficiency: 9, difficulty: 9, liquidity: 3, icon: Wheat },
  { name: "Live Cattle", symbol: "LE", venue: "CME", group: "Livestock", drivers: "Herd size, beef demand, feed costs, packing margins", inefficiency: 7, difficulty: 8, liquidity: 7, icon: Beef },
  { name: "Feeder Cattle", symbol: "GF", venue: "CME", group: "Livestock", drivers: "Corn price, pasture, drought, herd liquidation", inefficiency: 8, difficulty: 9, liquidity: 6, icon: Beef },
  { name: "Lean Hogs", symbol: "HE", venue: "CME", group: "Livestock", drivers: "Herd disease, pork demand, exports, processing margins", inefficiency: 7, difficulty: 8, liquidity: 6, icon: Beef },
  { name: "Natural Gas", symbol: "NG", venue: "NYMEX/CME", group: "Energy", drivers: "Weather, storage, LNG exports, production, pipelines", inefficiency: 6, difficulty: 9, liquidity: 9, icon: Flame },
  { name: "Crude Oil", symbol: "CL", venue: "NYMEX/CME", group: "Energy", drivers: "OPEC, inventories, geopolitics, refinery demand", inefficiency: 4, difficulty: 9, liquidity: 10, icon: Droplets },
  { name: "Copper", symbol: "HG", venue: "COMEX/CME", group: "Metals", drivers: "China demand, inventories, mine supply, global growth", inefficiency: 5, difficulty: 8, liquidity: 8, icon: BarChart3 },
  { name: "Gold", symbol: "GC", venue: "COMEX/CME", group: "Metals", drivers: "Rates, dollar, real yields, risk sentiment", inefficiency: 3, difficulty: 7, liquidity: 10, icon: DollarSign },
  { name: "Lumber", symbol: "LBR/LBS", venue: "CME", group: "Niche", drivers: "Housing starts, mill supply, inventory, rates", inefficiency: 8, difficulty: 9, liquidity: 3, icon: Layers }
];

const glossary = [
  ["Basis", "Local cash price minus futures price. A key physical-market signal."], ["Backwardation", "A futures curve where nearby contracts trade above deferred contracts, often signaling scarcity."], ["Calendar spread", "Long one contract month and short another in the same commodity."], ["Contango", "A futures curve where deferred contracts trade above nearby contracts, often reflecting storage and financing costs."], ["COT", "Commitments of Traders report showing futures positioning by trader category."], ["First Notice Day", "The first day a long futures holder may be assigned delivery notice in physically deliverable contracts."], ["Front month", "The nearest active futures contract."], ["Hedger", "A participant using futures to reduce physical business risk."], ["Initial margin", "Collateral required to open a futures position."], ["Maintenance margin", "Minimum account equity required to maintain a futures position."], ["Mark-to-market", "Daily settlement of gains and losses."], ["Open interest", "Number of outstanding futures contracts not yet closed or delivered."], ["Roll", "Closing an expiring contract and opening a later contract."], ["Tick", "The minimum price movement of a contract."], ["Tick value", "Dollar value of one tick movement."], ["WASDE", "USDA World Agricultural Supply and Demand Estimates report."], ["Yield", "Agricultural output per acre, central to crop supply estimates."], ["Convenience yield", "Non-monetary value of holding physical inventory during scarcity."], ["Limit move", "Exchange-imposed maximum daily price move for some contracts."], ["Slippage", "Difference between expected execution price and actual execution price."]
];

const quizzes = [
  { q: "What is the most important thing to know before trading a new futures contract?", options: ["The company CEO", "Tick value and contract specs", "The 52-week high", "Dividend yield"], answer: 1 },
  { q: "Backwardation usually suggests:", options: ["Deferred supply is more valuable than nearby supply", "Nearby scarcity or strong immediate demand", "The market is closed", "No storage costs exist"], answer: 1 },
  { q: "A calendar spread is:", options: ["Trading the same commodity across different months", "Trading stocks against bonds", "Buying physical inventory", "A weather forecast"], answer: 0 },
  { q: "The COT report is mainly useful for understanding:", options: ["Exchange holidays", "Trader positioning", "Crop disease", "Broker commissions"], answer: 1 },
  { q: "Your LLM agent should focus most on:", options: ["Directly executing trades", "Detecting what changed versus prior expectations", "Predicting exact prices to the penny", "Ignoring source quality"], answer: 1 }
];

function Rating({ label, value }) { return <div><div className="flex justify-between text-xs uppercase tracking-wide text-zinc-500 mb-1"><span>{label}</span><span>{value}/10</span></div><div className="h-2 bg-zinc-200 rounded-full overflow-hidden"><div className="h-full bg-zinc-900" style={{ width: `${value * 10}%` }} /></div></div>; }

function ModuleView() {
  const [active, setActive] = useState(modules[0].id); const [lessonIndex, setLessonIndex] = useState(0); const mod = modules.find(m => m.id === active); const lesson = mod.lessons[lessonIndex]; const Icon = mod.icon;
  return <div className="grid lg:grid-cols-[320px_1fr] gap-5"><div className="space-y-2">{modules.map(m => { const MIcon = m.icon; const selected = active === m.id; return <button key={m.id} onClick={() => { setActive(m.id); setLessonIndex(0); }} className={`w-full text-left p-4 border rounded-2xl transition ${selected ? "bg-zinc-900 text-white border-zinc-900" : "bg-white hover:bg-zinc-50 border-zinc-200"}`}><div className="flex gap-3 items-start"><MIcon className="w-5 h-5 mt-0.5" /><div><div className="font-semibold">{m.title}</div><div className={`text-sm mt-1 ${selected ? "text-zinc-300" : "text-zinc-500"}`}>{m.summary}</div></div></div></button>; })}</div><Card className="rounded-3xl shadow-sm"><CardContent className="p-7"><div className="flex items-center gap-3 mb-4"><div className="p-3 bg-zinc-100 rounded-2xl"><Icon className="w-6 h-6" /></div><div><h2 className="text-2xl font-bold">{mod.title}</h2><p className="text-zinc-500">Lesson {lessonIndex + 1} of {mod.lessons.length}</p></div></div><AnimatePresence mode="wait"><motion.div key={`${active}-${lessonIndex}`} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.2 }} className="min-h-[300px]"><h3 className="text-xl font-semibold mb-3">{lesson.title}</h3><p className="text-lg leading-8 text-zinc-700">{lesson.body}</p><div className="mt-6 p-5 rounded-2xl bg-amber-50 border border-amber-200 flex gap-3"><AlertTriangle className="w-5 h-5 mt-1 shrink-0" /><div><div className="font-semibold">Key takeaway</div><div className="text-zinc-700 mt-1">{lesson.takeaway}</div></div></div></motion.div></AnimatePresence><div className="flex justify-between mt-8"><Button variant="outline" className="rounded-2xl" disabled={lessonIndex === 0} onClick={() => setLessonIndex(i => i - 1)}><ChevronLeft className="w-4 h-4 mr-1 inline" />Previous</Button><Button className="rounded-2xl" disabled={lessonIndex === mod.lessons.length - 1} onClick={() => setLessonIndex(i => i + 1)}>Next<ChevronRight className="w-4 h-4 ml-1 inline" /></Button></div></CardContent></Card></div>;
}

function MarketMap() { const [group, setGroup] = useState("All"); const groups = ["All", ...Array.from(new Set(markets.map(m => m.group)))]; const visible = group === "All" ? markets : markets.filter(m => m.group === group); return <div><div className="flex flex-wrap gap-2 mb-5">{groups.map(g => <Button key={g} onClick={() => setGroup(g)} variant={group === g ? "default" : "outline"} className="rounded-2xl">{g}</Button>)}</div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{visible.map(m => { const Icon = m.icon; return <Card key={m.symbol} className="rounded-3xl shadow-sm hover:shadow-md transition"><CardContent className="p-5 space-y-4"><div className="flex justify-between items-start"><div><div className="text-xl font-bold">{m.name}</div><div className="text-sm text-zinc-500">{m.symbol} · {m.venue} · {m.group}</div></div><div className="p-3 bg-zinc-100 rounded-2xl"><Icon className="w-5 h-5" /></div></div><p className="text-sm text-zinc-700 min-h-[60px]"><strong>Drivers:</strong> {m.drivers}</p><Rating label="Inefficiency" value={m.inefficiency} /><Rating label="Difficulty" value={m.difficulty} /><Rating label="Liquidity" value={m.liquidity} /></CardContent></Card>; })}</div></div>; }

function CalculatorPanel() { const [price, setPrice] = useState(450); const [size, setSize] = useState(5000); const [move, setMove] = useState(0.05); const notional = price * size; const pnl = move * size; return <Card className="rounded-3xl shadow-sm"><CardContent className="p-7"><div className="flex items-center gap-3 mb-5"><Calculator className="w-6 h-6" /><h2 className="text-2xl font-bold">Futures P&L Sandbox</h2></div><div className="grid md:grid-cols-3 gap-4"><label className="space-y-2"><span className="text-sm font-medium">Price</span><input type="number" value={price} onChange={e => setPrice(Number(e.target.value))} className="w-full p-3 rounded-2xl border" /></label><label className="space-y-2"><span className="text-sm font-medium">Contract size</span><input type="number" value={size} onChange={e => setSize(Number(e.target.value))} className="w-full p-3 rounded-2xl border" /></label><label className="space-y-2"><span className="text-sm font-medium">Price move</span><input type="number" step="0.01" value={move} onChange={e => setMove(Number(e.target.value))} className="w-full p-3 rounded-2xl border" /></label></div><div className="grid md:grid-cols-2 gap-4 mt-6"><div className="p-5 rounded-2xl bg-zinc-100"><div className="text-sm text-zinc-500">Notional exposure</div><div className="text-3xl font-bold">${notional.toLocaleString()}</div></div><div className="p-5 rounded-2xl bg-zinc-900 text-white"><div className="text-sm text-zinc-300">P&L from move</div><div className="text-3xl font-bold">${pnl.toLocaleString()}</div></div></div><p className="mt-4 text-sm text-zinc-500">Example: for corn, contract size is 5,000 bushels. A 5-cent move equals $250 per contract.</p></CardContent></Card>; }

function Glossary() { const [query, setQuery] = useState(""); const filtered = glossary.filter(([term, def]) => `${term} ${def}`.toLowerCase().includes(query.toLowerCase())); return <Card className="rounded-3xl shadow-sm"><CardContent className="p-7"><div className="flex items-center gap-3 mb-5"><Search className="w-6 h-6" /><h2 className="text-2xl font-bold">Searchable Glossary</h2></div><input placeholder="Search terms..." value={query} onChange={e => setQuery(e.target.value)} className="w-full p-4 rounded-2xl border mb-5" /><div className="grid md:grid-cols-2 gap-3">{filtered.map(([term, def]) => <div key={term} className="p-4 rounded-2xl border bg-white"><div className="font-bold">{term}</div><div className="text-sm text-zinc-600 mt-1">{def}</div></div>)}</div></CardContent></Card>; }

function Quiz() { const [answers, setAnswers] = useState({}); const score = Object.entries(answers).filter(([i, a]) => quizzes[Number(i)].answer === a).length; return <Card className="rounded-3xl shadow-sm"><CardContent className="p-7"><div className="flex items-center gap-3 mb-5"><GraduationCap className="w-6 h-6" /><h2 className="text-2xl font-bold">Knowledge Check</h2></div><div className="mb-5 p-4 rounded-2xl bg-zinc-100">Score: <strong>{score}/{quizzes.length}</strong></div><div className="space-y-5">{quizzes.map((q, i) => <div key={q.q} className="p-5 rounded-2xl border"><div className="font-semibold mb-3">{i + 1}. {q.q}</div><div className="grid md:grid-cols-2 gap-2">{q.options.map((opt, j) => { const chosen = answers[i] === j; const correct = q.answer === j; const show = answers[i] !== undefined; return <button key={opt} onClick={() => setAnswers(a => ({ ...a, [i]: j }))} className={`text-left p-3 rounded-2xl border flex items-center justify-between ${chosen ? "bg-zinc-900 text-white" : "bg-white"}`}>{opt}{show && chosen && (correct ? <CheckCircle2 className="w-5 h-5" /> : <XCircle className="w-5 h-5" />)}</button>; })}</div></div>)}</div></CardContent></Card>; }

function Roadmap() { const weeks = [["Week 1", "Contract specs", "Pick 10 contracts. Learn symbol, venue, tick value, contract size, months, first notice day, and daily limit rules."], ["Week 2", "Market drivers", "For each contract, write the top 5 supply drivers, top 5 demand drivers, and top 5 recurring reports."], ["Week 3", "Curve literacy", "Track front month, second month, six-month deferred, and key calendar spreads every day."], ["Week 4", "Reports", "Build a release calendar for WASDE, crop progress, export sales, COT, EIA, and relevant international reports."], ["Week 5", "Signal journal", "Log every thesis before market reaction: source, direction, confidence, time horizon, and invalidation."], ["Week 6", "Agent prototype", "Use LLMs to summarize reports, compare against prior state, and produce structured signal cards."], ["Week 7", "Paper execution", "Paper trade only. Track slippage, timing, drawdown, and whether the signal was early or wrong."], ["Week 8", "Live micro-sizing", "Only after 50+ logged signals. Trade smallest viable size and keep the agent as analyst, not executor."]]; return <div className="grid md:grid-cols-2 gap-4">{weeks.map(([w, title, desc]) => <Card key={w} className="rounded-3xl shadow-sm"><CardContent className="p-5"><div className="text-sm text-zinc-500">{w}</div><div className="text-xl font-bold mt-1">{title}</div><p className="text-zinc-700 mt-2">{desc}</p></CardContent></Card>)}</div>; }

export default function CommodityFuturesLearningApp() {
  const [tab, setTab] = useState("learn");
  const tabs = [["learn", "Course", BookOpen], ["markets", "Market Map", Map], ["calc", "P&L Sandbox", Calculator], ["glossary", "Glossary", Search], ["quiz", "Quiz", GraduationCap], ["roadmap", "Roadmap", Clock]];
  return <div className="min-h-screen bg-[#f7f3ea] text-zinc-950 p-4 md:p-8"><div className="max-w-7xl mx-auto"><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mb-8"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-zinc-900 text-white text-sm mb-4"><BarChart3 className="w-4 h-4" /> Commodity Futures Masterclass</div><h1 className="text-4xl md:text-6xl font-black tracking-tight max-w-4xl">Learn the systems, language, markets, and mechanics of commodity futures.</h1><p className="text-lg text-zinc-600 mt-4 max-w-3xl">An interactive training environment for building intuition before designing an always-on futures intelligence system.</p></motion.div><div className="flex flex-wrap gap-2 mb-6">{tabs.map(([id, label, Icon]) => <Button key={id} onClick={() => setTab(id)} variant={tab === id ? "default" : "outline"} className="rounded-2xl"><Icon className="w-4 h-4 mr-2 inline" />{label}</Button>)}</div><AnimatePresence mode="wait"><motion.div key={tab} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.18 }}>{tab === "learn" && <ModuleView />}{tab === "markets" && <MarketMap />}{tab === "calc" && <CalculatorPanel />}{tab === "glossary" && <Glossary />}{tab === "quiz" && <Quiz />}{tab === "roadmap" && <Roadmap />}</motion.div></AnimatePresence></div></div>;
}
